spring.application.name=Med-Trace-Backend

spring.datasource.url=jdbc:mysql://localhost:3306/med_trace_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=savi11@28
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8085